### PR TITLE
Fixing a test error with CCM*

### PR DESCRIPTION
**Pull request by hannestschofenig**

### CODE REVIEW

**Comment by zhihan** [comment]
Confirmed that ccm-suite is fixed by this change.

**Comment by zhihan** [comment]
Thanks for fixing it!

**Review by zhihan — APPROVED** [review]
LGTM

**Review by hanno-becker — CHANGES_REQUESTED** [review]
@hannestschofenig Could you explain a bit more how this fixes the tests in question?

**Comment by hanno-becker** [comment]
The change which is reverted here was initially made by me as a temporary fix to address a GCC-10 compiler problem with the CCM test suite, which has since been fixed in upstream Mbed TLS through https://github.com/ARMmbed/mbedtls/pull/4126.

We should merge `development` into `tls13-prototype` before merging this PR to keep the build working for GCC 10.

**Comment by hanno-becker** [comment]
Merging `development` highly non-trivial due to change in example programs.

I have cherry-picked the exact commit fixing the build problem with GCC-10. Together with this, the PR is fine.

**Review by hanno-becker — APPROVED** [review]

**Pull request merged**
