### PR TITLE
Check use_psk when generate early secret.

### PR DESCRIPTION
**Pull request by lhuang04**
Summary:
Before [PR 239](https://github.com/hannestschofenig/mbedtls/commit/719928c24a6e5d73c56c58513bd6beafe6072e22#diff-b67c0adff0a54f6cc5e2401f775e88ab9a2946c4e2e1c5c9cf07f3222a5f2eacL1175-L1189), we will check the `key_exchange` when we create `early_secret` for `mbedtls_ssl_tls1_3_derive_master_secret`. We shouldn't use `psk` unless `key_exchange`  is `MBEDTLS_KEY_EXCHANGE_PSK` or `MBEDTLS_KEY_EXCHANGE_ECDHE_PSK`.

We changed to always use psk when we do `mbedtls_ssl_tls1_3_key_schedule_stage_early_data`. This breaks when early data is rejected by server, and client can't fall back to 1-RTT. When client tried to fall back to 1-RTT after server reject the early data, the psk shouldn't be used in  `mbedtls_ssl_tls1_3_key_schedule_stage_early_data`.

Test Plan:
* `ssl-opt.sh`
* repo :
1. server enables early data.
2. client connects to server and then store the psk.
3. server disables early data.
4. client disconnects, and re-connects to server with early data.
5. server reject early data, client fall back to 1-RTT.

Reviewers:

Subscribers:

Tasks:

Tags:

Notes:
* Pull requests cannot be accepted until the PR follows the [contributing guidelines](../CONTRIBUTING.md). In particular, each commit must have at least one `Signed-off-by:` line from the committer to certify that the contribution is made under the terms of the [Developer Certificate of Origin](../dco.txt).
* This is just a template, so feel free to use/remove the unnecessary things
## Description
A few sentences describing the overall goals of the pull request's commits.

## Status
**READY/IN DEVELOPMENT/HOLD**

## Requires Backporting
When there is a bug fix, it should be backported to all maintained and supported branches.
Changes do not have to be backported if:
- This PR is a new feature\enhancement
- This PR contains changes in the API. If this is true, and there is a need for the fix to be backported, the fix should be `handled differently in the legacy branch

Yes | NO  
Which branch?

## Migrations
If there is any API change, what's the incentive and logic for it.

YES | NO

## Additional comments
Any additional information that could be of interest

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated
- [ ] Backported

## Steps to test or reproduce
Outline the steps to test or reproduce the PR here.

### CODE REVIEW

**Review by hanno-becker — CHANGES_REQUESTED** [review]
Thank you @lhuang04 for catching this.

As for the fix, it is the intend of `get_psk()` that is should incorporate any logic about whether PSKs are actually in use or not.

Can you think about how to incorporate the logic you've added into `get_psk()`, so we don't have to change the key derivation code?

**Comment by lhuang04** [comment]
@hanno-arm , there are 5 places call `mbedtls_ssl_get_psk`. It looks hard to incorporate all different cases into it.
1. [mbedtls_ssl_write_pre_shared_key_ext](https://github.com/hannestschofenig/mbedtls/blob/tls13-prototype/library/ssl_tls13_client.c#L801)
2. [ssl_parse_server_psk_identity_ext](https://github.com/hannestschofenig/mbedtls/blob/tls13-prototype/library/ssl_tls13_client.c#L1947)
3. [mbedtls_ssl_tls1_3_key_schedule_stage_early_data](https://github.com/hannestschofenig/mbedtls/blob/tls13-prototype/library/ssl_tls13_keys.c#L1228)
4. [mbedtls_ssl_parse_client_psk_identity_ext](https://github.com/hannestschofenig/mbedtls/blob/tls13-prototype/library/ssl_tls13_server.c#L837)
5. [ssl_write_server_pre_shared_key_ext](https://github.com/hannestschofenig/mbedtls/blob/tls13-prototype/library/ssl_tls13_server.c#L917)

In case 3, we have two sub cases:
3.1 `mbedtls_ssl_tls1_3_key_schedule_stage_early_data` is called by `ssl_write_early_data_prepare`
3.2 `mbedtls_ssl_tls1_3_key_schedule_stage_early_data`  is called by `ssl_server_hello_postprocess`

Things we want to fix is restoring the `key_exchange` check for case 3.2. I have thought about checking the `state` inside `mbedtls_ssl_get_psk` , but case 1 is in the same state of case 3.2, and it can't have such  `key_exchange` check.

One alternative is to push my current change into `mbedtls_ssl_tls1_3_key_schedule_stage_early_data`. What do you think?

Something like this
```
diff --git a/xplat/mobilenetwork/third-party/mbedtls/library/ssl_tls13_keys.c b/xplat/mobilenetwork/third-party/mbedtls/library/ssl_tls13_keys.c
--- a/xplat/mobilenetwork/third-party/mbedtls/library/ssl_tls13_keys.c
+++ b/xplat/mobilenetwork/third-party/mbedtls/library/ssl_tls13_keys.c
@@ -1222,10 +1222,13 @@
int mbedtls_ssl_tls1_3_key_schedule_stage_early_data(
    mbedtls_ssl_context *ssl, int use_psk )
{
     int ret = 0;
     mbedtls_md_type_t const md_type = ssl->handshake->ciphersuite_info->mac;
 
-    unsigned char const *psk;
-    size_t psk_len;
-
-    mbedtls_ssl_get_psk( ssl, &psk, &psk_len );
+    unsigned char const *psk = NULL;
+    size_t psk_len = 0;
+    if( ssl->state != MBEDTLS_SSL_SERVER_HELLO ||
+.           ssl->session_negotiate->key_exchange == MBEDTLS_KEY_EXCHANGE_PSK ||
+            ssl->session_negotiate->key_exchange == MBEDTLS_KEY_EXCHANGE_ECDHE_PSK )
+    {
+        mbedtls_ssl_get_psk( ssl, &psk, &psk_len );
+    }
 
     ret = mbedtls_ssl_tls1_3_evolve_secret( md_type,
                               NULL,          /* Old secret */
```

**Comment by hanno-becker** [comment]
Thanks for investigating this, @lhuang04. I think you uncovered that `get_psk()` blurs (a) access to the (potentially multiple) PSKs configured prior to the handshake (b) access to the _single_ PSK (potentially `NULL`) that has been negotiated for use during the handshake. If we have offered a PSK but aren't using it, we run into the issue you describe. The fact that we currently only allow to configure a single PSK to offer doesn't help the separation of (a) and (b).

I feel that there's no place for `get_psk()` as we have it now. Instead, we want to either iterate over the configured PSKs -- external or resumption/ticket or both, each potentially multiple times -- or we want to use _the_ specific PSK that the handshake is going to use.

To better separate (a) and (b), I think for (b) should aim at _always_ setting `ssl->handshake->psk` to the PSK we're using for the current handshake, potentially `NULL`. Then, `mbedtls_ssl_tls1_3_key_schedule_stage_early_data()` can unconditionally use this PSK. 

For (a), we will ultimately need an iterator over the configured PSKs, but for now I suggest to introduce a getter which checks whether a PSK should be offered, and if so returns this PSK + its PSK identity. 

I have created https://github.com/hannestschofenig/mbedtls/pull/263 with a fix along those lines.

@lhuang04 Could you review this and in particular check that it fixes the previously failing test?

**Comment by lhuang04** [comment]
will be fixed via #263

**Pull request closed without merging**
